name: Publish Docker image
on:
  push:
    branches: main
  release:
    types: [published]
defaults:
  run:
   working-directory: ./src/sh-ci
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag arpan1323/test:v3
      - name: Push the tagged Docker image
        run: docker push arpan1323/test:v3
